server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA — sve rute idu na index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Agresivno keširanje statičkih fajlova
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
